version: '3.7'

services:
  db:
    container_name: db_container
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - app-network
    restart: unless-stopped
  
  dbadmin:
    container_name: dbadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DBADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DBADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${DBADMIN_PORT}:80"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - db
  
  server:
    container_name: server_container
    build: ./server
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./server/:/app
    command: gunicorn server.app:app -b :8080 --worker-class aiohttp.worker.GunicornWebWorker --reload
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db
  
  webserver:
    container_name: webserver_container
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: